<?php
require __DIR__ . '/purge-regression.php';
function sanitize_key($s){return preg_replace('/[^a-z0-9_-]/','',strtolower($s));}
function get_main_site_id(){return 1;}
class QueueDB extends DB {
    public $queue=false;
    function get_blog_prefix($id){return 'wp_';}
    function get_var($q){return $this->queue===false?null:serialize($this->queue);}
    function query($q){[$sql,$a]=$q;if(in_array(ACFCM_Network_Queue::KEY,$a,true)){
        if(strpos($sql,'INSERT IGNORE')===0){if($this->queue!==false)return 0;$this->queue=unserialize($a[1]);return 1;}
        [$new,$key,$old]=$a;if(serialize($this->queue)!==$old)return 0;$this->queue=unserialize($new);return 1;
    }return parent::query($q);}
}
$GLOBALS['wpdb']=new QueueDB;
if(!class_exists('WpeCommon')){class WpeCommon{static function http_to_varnish($m,$h,$headers){$GLOBALS['origins'][]=[get_current_blog_id(),$h,$headers];if(isset($GLOBALS['origin_callback'])){$f=$GLOBALS['origin_callback'];unset($GLOBALS['origin_callback']);$f();}return $GLOBALS['origin_response']??null;}}}
class_alias('ACFCM_Network_Queue','Q');
function qreset(){reset_state();$GLOBALS['wpdb']->queue=false;$GLOBALS['origins']=[];$GLOBALS['multi']=true;unset($GLOBALS['origin_response'],$GLOBALS['origin_callback']);switch_to_blog(2);update_option('cloudflare_zone_id','zone-1');update_option('cloudflare_api_token','second');restore_current_blog();}
function due($all=false){$s=Q::state();$s['quiet_until']=0;$s['updating']=[];$s['hold_until']=0;$s['next_origin']=0;$s['next_edge']=0;if($all)$s['lease']=null;foreach($s['targets'] as &$t)$t['due']=time()-10000;unset($t);$GLOBALS['wpdb']->queue=$s;}
qreset();for($i=0;$i<20;$i++){P::purge_network_after_wp_update(null,['action'=>'update','type'=>'plugin']);P::purge_network_after_automatic_updates(['plugin'=>[1]]);}check(count(Q::state()['targets'])===2&&!$GLOBALS['origins']&&!$GLOBALS['calls'],'bulk/background hooks coalesce without synchronous purge');
Q::tick();check(!$GLOBALS['origins'],'initial debounce prevents dispatch during update burst');due();Q::tick();check(count($GLOBALS['origins'])===1&&!$GLOBALS['calls'],'one origin before edge');Q::tick();check(count($GLOBALS['origins'])===1&&!$GLOBALS['calls'],'overdue targets cannot catch up in a burst');$s=Q::state();check($s['next_origin']>=time()+119,'origin spacing reserved from actual dispatch');$s['targets'][1]['due']=time()-1;$GLOBALS['wpdb']->queue=$s;Q::tick();check(count($GLOBALS['calls'])===1&&$GLOBALS['calls'][0][2]===['hosts'=>['site1.test']],'shared zone edge purge targets just the first hostname');due();Q::tick();check(count($GLOBALS['origins'])===2&&$GLOBALS['origins'][1][0]===2,'shared zone preserves second origin scope');due();Q::tick();check(count($GLOBALS['calls'])===2&&$GLOBALS['calls'][1][2]===['hosts'=>['site2.test']],'second mapped hostname gets separate paced edge purge');
qreset();Q::enqueue('manual_network');due();$GLOBALS['origin_callback']=function(){Q::tick();$s=Q::state();$s['targets'][1]['generation']++;$s['quiet_until']=time()+180;$GLOBALS['wpdb']->queue=$s;};Q::tick();check(count($GLOBALS['origins'])===1&&Q::state()['targets'][1]['generation']===2,'overlapping worker cannot claim and update during origin survives');
qreset();Q::enqueue('update');due();Q::control('pause');Q::enqueue('repeat');Q::tick();check(!$GLOBALS['origins']&&Q::state()['paused'],'pause persists across new update hooks');Q::control('resume');due();Q::tick();check(count($GLOBALS['origins'])===1,'resume starts at most one origin');Q::control('cancel');Q::tick();check(!Q::state()['lease']&&Q::state()['cancelled']&&!$GLOBALS['calls'],'cancel blocks undispatched edge stages');Q::enqueue('new_update');Q::tick();check(count($GLOBALS['origins'])===1,'cancel stays stopped for subsequent hooks');
qreset();Q::enqueue('update');due();$GLOBALS['origin_response']=new WP_Error();Q::tick();check(!$GLOBALS['calls']&&Q::state()['hold_until']>=time()+119,'origin failure blocks edge and backs off whole maintenance queue');Q::tick();check(count($GLOBALS['origins'])===1,'backoff prevents next site origin');
qreset();Q::enqueue('update');due();Q::tick();$s=Q::state();$s['targets'][1]['due']=time()-1;$GLOBALS['wpdb']->queue=$s;$GLOBALS['responses']=[['code'=>429,'retry-after'=>'900','body'=>'{}']];Q::tick();check(Q::state()['hold_until']>=time()+899,'Cloudflare Retry-After controls global maintenance backoff');
qreset();Q::enqueue('update');due();$s=Q::state();$s['lease']=['site'=>'1','token'=>'dead-worker','until'=>time()+100];$GLOBALS['wpdb']->queue=$s;Q::tick();check(!$GLOBALS['origins'],'persisted lease survives restart');$s['lease']['until']=time()-1;$GLOBALS['wpdb']->queue=$s;Q::tick();check(count($GLOBALS['origins'])===1,'expired worker lease recovers without batch drain');
qreset();Q::enqueue('update');due();Q::tick();$s=Q::state();$s['targets'][1]['due']=time()-1;$GLOBALS['wpdb']->queue=$s;$GLOBALS['during_http']=function(){Q::enqueue('new_update');};Q::tick();check(Q::state()['targets'][1]['stage']==='origin','new update during edge leaves one trailing origin pass');
qreset();Q::enqueue('update');due();Q::tick();P::purge_urls_for_current_site([home_url('/edited/')],true);check(count(jobs())===1,'content edit gets independent durable URL job during broad rollout');Q::control('pause');retry_now();retry_now();check(count($GLOBALS['calls'])===1&&isset($GLOBALS['calls'][0][2]['files']),'paused maintenance does not delay content freshness');
qreset();Q::enqueue('update');due();update_option('cloudflare_zone_id','changed');Q::tick();check(!$GLOBALS['origins']&&!$GLOBALS['calls']&&Q::state()['targets'][1]['stage']==='failed','changed mapping fails closed without purging old zone');
qreset();$GLOBALS['home_path']='/subsite';Q::enqueue('update');check(Q::state()['targets'][1]['error']==='scope_review_required','subdirectory scope blocks instead of broadening hostname purge');unset($GLOBALS['home_path']);
qreset();Q::enqueue('update');$GLOBALS['events']=[];Q::recover();check((bool)wp_next_scheduled(Q::HOOK,[]),'missing cron event repaired from durable state');
qreset();update_site_option('acfcm_network_update_types',['theme']);P::purge_network_after_automatic_updates(['plugin'=>[1]]);check(!Q::state(),'background completion respects selected update types');
class Plugin_Upgrader {} class Theme_Upgrader {} class Core_Upgrader {}
qreset();Q::control('pause');check(Q::state()['paused'],'hold can be enabled before any update exists');
foreach([new Plugin_Upgrader(),new Theme_Upgrader(),new Core_Upgrader()] as $upgrader){Q::before_download(false,'test-package',$upgrader,[]);Q::enqueue('update_complete');due();Q::tick();}
check(!$GLOBALS['origins']&&count(Q::state()['targets'])===2,'held plugins then themes then core share one queue even across long human gaps');Q::control('resume');Q::tick();check(!$GLOBALS['origins']&&Q::state()['quiet_until']>=time()+179,'updates finished still observes quiet period');due();Q::tick();check(count($GLOBALS['origins'])===1,'final settled session starts one paced rollout');
qreset();check(Q::before_download(false,'test-package',new Plugin_Upgrader(),[])===false,'start filter preserves updater response');$s=Q::state();check(count($s['updating'])===1&&max($s['updating'])>=time()+899,'interrupted update has bounded durable lease');Q::tick();check(!$GLOBALS['origins'],'active updater blocks dispatch');Q::enqueue('plugin_complete');check(!Q::state()['updating'],'completion releases same-request updater lease');$first=Q::state()['quiet_until'];Q::before_download(false,'test-package',new Theme_Upgrader(),[]);Q::enqueue('theme_complete');check(Q::state()['quiet_until']>=$first&&!$GLOBALS['origins'],'short plugin-to-theme gap renews quiet period');due();Q::tick();Q::before_download(false,'test-package',new Core_Upgrader(),[]);check(Q::state()['targets'][1]['stage']==='origin','long gap and subsequent core start revoke old edge readiness');Q::tick();check(!$GLOBALS['calls'],'old-generation edge cannot run while new update is active');
qreset();Q::enqueue('update');due();Q::tick();$s=Q::state();$s['targets'][1]['due']=time()-1;$GLOBALS['wpdb']->queue=$s;Q::tick();check(Q::state()['targets'][1]['stage']==='done','site initially processed');Q::before_download(false,'test-package',new Theme_Upgrader(),[]);check(Q::state()['targets'][1]['stage']==='origin'&&Q::state()['targets'][2]['stage']==='origin','new update refreshes completed sites and coalesces untouched pending sites');
qreset();Q::before_download(false,'test-package',new Plugin_Upgrader(),[]);$s=Q::state();$s['quiet_until']=time()-1;foreach($s['updating'] as &$until)$until=time()-181;unset($until);foreach($s['targets'] as &$target)$target['due']=time()-1;unset($target);$GLOBALS['wpdb']->queue=$s;Q::tick();check(count($GLOBALS['origins'])===1,'missing completion recovers after updater lease plus quiet period');
qreset();$GLOBALS['home_urls']=[2=>'https://site1.test'];Q::enqueue('update');check(Q::state()['targets'][1]['error']==='scope_review_required'&&Q::state()['targets'][2]['error']==='scope_review_required','shared hostname is blocked on both sites without broad fallback');unset($GLOBALS['home_urls']);Q::enqueue('mapping_reviewed');check(Q::state()['targets'][1]['stage']==='origin','corrected shared-host inventory can be explicitly requeued');
qreset();Q::enqueue('update');due();Q::tick();$s=Q::state();$s['targets'][1]['due']=time()-1;$GLOBALS['wpdb']->queue=$s;$GLOBALS['responses']=[['code'=>403,'body'=>'{}']];Q::tick();check(Q::state()['targets'][1]['stage']==='failed','unsupported hostname purge fails without zone-wide fallback');Q::control('retry_failed');check(Q::state()['targets'][1]['stage']==='origin','controlled retry restarts failed scope through origin');
$code=file_get_contents(dirname(__DIR__).'/includes/class-acfcm-network-queue.php');check(strpos($code,'wp_cache_flush')===false&&strpos($code,'purge_memcached')===false,'maintenance implementation never flushes object cache');
echo "All maintenance queue regressions passed.\n";
