<?php
// Deterministic WordPress/HTTP test doubles; no network or WordPress installation needed.
define('ABSPATH', __DIR__); define('DAY_IN_SECONDS', 86400); define('MINUTE_IN_SECONDS', 60);
$GLOBALS['blog']=1; $GLOBALS['multi']=false; $GLOBALS['opts']=[]; $GLOBALS['net']=[]; $GLOBALS['events']=[]; $GLOBALS['posts']=[]; $GLOBALS['calls']=[]; $GLOBALS['responses']=[]; $GLOBALS['hooks']=[];
function add_action($h,$f,$p=10,$n=1){$GLOBALS['hooks'][$h][]=[$f,$n];} function add_filter(...$a){} function register_activation_hook(...$a){}
function fire($h,...$args){$before=count($GLOBALS['calls']);foreach($GLOBALS['hooks'][$h]??[] as [$f,$n])call_user_func_array($f,array_slice($args,0,$n));if($h==='shutdown'){if(count($GLOBALS['calls'])!==$before)throw new RuntimeException('Shutdown must not send HTTP');foreach(array_keys($GLOBALS['opts']) as $blog){$original=$GLOBALS['blog'];$GLOBALS['blog']=$blog;retry_now();$GLOBALS['blog']=$original;}}}
function get_current_network_id(){return 1;}
function get_current_blog_id(){return $GLOBALS['blog'];} function is_multisite(){return $GLOBALS['multi'];}
function switch_to_blog($id){$GLOBALS['stack'][]=$GLOBALS['blog'];$GLOBALS['blog']=$id;} function restore_current_blog(){$GLOBALS['blog']=array_pop($GLOBALS['stack']);}
function get_option($k,$d=false){return $GLOBALS['opts'][$GLOBALS['blog']][$k]??$d;}
function update_option($k,$v,...$a){$GLOBALS['opts'][$GLOBALS['blog']][$k]=$v;return true;}
function add_option($k,$v,...$a){if(get_option($k)!==false)return false;return update_option($k,$v);}
function get_site_option($k,$d=false){return $GLOBALS['net'][$k]??$d;} function update_site_option($k,$v){$GLOBALS['net'][$k]=$v;}
function get_site_transient($k){return get_site_option($k);} function set_site_transient($k,$v,$t){update_site_option($k,$v);} function delete_site_transient($k){unset($GLOBALS['net'][$k]);}
function maybe_unserialize($v){return unserialize($v);} function maybe_serialize($v){return serialize($v);} function wp_cache_delete(...$a){if(isset($GLOBALS['object_delete']))return ($GLOBALS['object_delete'])(...$a);}
class DB {public $options='options'; function get_results($sql){$rows=[];foreach($GLOBALS['opts'][$GLOBALS['blog']]??[] as $k=>$v){if(strpos($k,'acfcm_purge_job_')===0)$rows[]=(object)['option_name'=>$k,'option_value'=>serialize($v)];}return $rows;} function prepare($q,...$a){return [$q,$a];} function query($q){[$sql,$a]=$q;if(strpos($sql,'INSERT IGNORE')===0){[$key,$new]=$a;if(get_option($key)!==false)return 0;update_option($key,unserialize($new));return 1;}$delete=strpos($sql,'DELETE')===0;if($delete){[$key,$old]=$a;}else{[$new,$key,$old]=$a;}if(serialize(get_option($key))!==$old)return 0;if($delete)unset($GLOBALS['opts'][$GLOBALS['blog']][$key]);else update_option($key,unserialize($new));return 1;}}
$GLOBALS['wpdb']=new DB;
function wp_generate_uuid4(){static $i=0;return 'uuid-'.++$i;} function wp_rand($a,$b){return $a;}
function event_key($h,$a){return $GLOBALS['blog'].$h.serialize($a);} function wp_next_scheduled($h,$a){return $GLOBALS['events'][event_key($h,$a)]??false;}
function wp_schedule_single_event($t,$h,$a,$err=false){if(!empty($GLOBALS['schedule_fail']))return false;$GLOBALS['events'][event_key($h,$a)]=$t;return true;}
function wp_clear_scheduled_hook($h,$a){unset($GLOBALS['events'][event_key($h,$a)]);}
function wp_json_encode($v,$flags=0){return json_encode($v,$flags);} function esc_url_raw($v){return filter_var($v,FILTER_VALIDATE_URL)?$v:'';}
function sanitize_text_field($v){return strip_tags($v);} function wp_parse_url($v,$component=-1){return parse_url($v,$component);} function current_time($v){return date('Y-m-d H:i:s');}
class WP_Error{function get_error_message(){return 'secret-test-token';}} function is_wp_error($v){return $v instanceof WP_Error;}
function wp_remote_request($url,$args){if(isset($GLOBALS['defense_mock']))return ($GLOBALS['defense_mock'])($url,$args);$GLOBALS['calls'][]=[$GLOBALS['blog'],$url,json_decode($args['body'],true)];if(isset($GLOBALS['during_http'])){$f=$GLOBALS['during_http'];unset($GLOBALS['during_http']);$f();}return array_shift($GLOBALS['responses'])??['code'=>200,'body'=>'{"success":true}'];}
function wp_remote_retrieve_response_code($r){return $r['code'];} function wp_remote_retrieve_body($r){return $r['body'];} function wp_remote_retrieve_response_message($r){return 'Remote response';} function wp_remote_retrieve_header($r,$k){return $r[$k]??'';}
function get_post($id){return $GLOBALS['posts'][$GLOBALS['blog']][$id]??null;} function get_post_status($id){return get_post($id)->post_status??false;}
function get_post_type($id){return get_post($id)->post_type??false;} function get_post_type_object($t){return (object)['public'=>$t==='post'];}
function wp_is_post_autosave($id){return false;} function wp_is_post_revision($id){return false;}
function home_url($p){return ($GLOBALS['home_urls'][$GLOBALS['blog']]??('https://site'.$GLOBALS['blog'].'.test')).($GLOBALS['home_path']??'').$p;} function get_permalink($id){$p=get_post($id);return $p?home_url('/'.$p->post_name.'/'):false;}
function trailingslashit($v){return rtrim($v,'/').'/';} function get_post_type_archive_link($t){return home_url('/archive/');}
function get_post_field($f,$id){return get_post($id)->$f??0;} function get_author_posts_url($id){return home_url('/author/'.$id.'/');}
function get_object_taxonomies(...$a){return [(object)['name'=>'category']];} function get_the_terms($id,$t){return [(object)['term_id'=>get_post($id)->term??1]];}
function get_term_link($t){return home_url('/category/'.$t->term_id.'/');} function rest_url($p){return home_url('/wp-json/'.$p);}
function get_post_thumbnail_id($id){return get_post($id)->thumb??0;} function wp_get_attachment_url($id){return home_url('/image-'.$id.'.jpg');}
require dirname(__DIR__).'/acquire-cloudflare-cache-manager.php';
class_alias('Acquire_Cloudflare_Cache_Manager','P');
function check($v,$message){if(!$v)throw new RuntimeException($message);echo "PASS $message\n";}
function reset_state(){P::flush_content_purges();$GLOBALS['blog']=1;$GLOBALS['multi']=false;$GLOBALS['opts']=[];$GLOBALS['events']=[];$GLOBALS['net']=[];$GLOBALS['calls']=[];$GLOBALS['responses']=[];update_option('cloudflare_zone_id','zone-1');update_option('cloudflare_api_token','secret-test-token');$GLOBALS['posts']=[1=>[7=>(object)['ID'=>7,'post_status'=>'publish','post_type'=>'post','post_name'=>'old','post_author'=>1,'term'=>1,'thumb'=>1]]];}
function files(){return array_merge(...array_map(fn($c)=>$c[2]['files']??[],$GLOBALS['calls']));}
function jobs(){return array_filter($GLOBALS['opts'][$GLOBALS['blog']]??[],fn($v,$k)=>strpos($k,'acfcm_purge_job_')===0,ARRAY_FILTER_USE_BOTH);}
function retry_now(){foreach(jobs() as $k=>$v){$v['due']=time()-1;update_option($k,$v);P::retry_purge($k,$v['id']);}}
reset_state();fire('save_post',7,get_post(7),false);check(!$GLOBALS['calls'],'publish waits for request completion');get_post(7)->thumb=9;fire('shutdown');check(in_array(home_url('/image-9.jpg'),files()),'publish collects late metadata');
reset_state();fire('pre_post_update',7);get_post(7)->post_name='new';get_post(7)->post_author=2;get_post(7)->term=2;fire('save_post',7,get_post(7),true);fire('save_post',7,get_post(7),true);fire('shutdown');foreach(['/old/','/new/','/category/1/','/category/2/','/author/1/','/author/2/'] as $u)check(in_array(home_url($u),files()),'old/new URL '.$u);check(count($GLOBALS['calls'])===1,'duplicate save hooks merge');
foreach(['trash','draft','private','future'] as $status){reset_state();fire('pre_post_update',7);get_post(7)->post_status=$status;get_post(7)->post_name='not-public';fire('save_post',7,get_post(7),true);fire('shutdown');check(in_array(home_url('/old/'),files())&&!in_array(home_url('/not-public/'),files()),'transition to '.$status);}
reset_state();fire('before_delete_post',7);unset($GLOBALS['posts'][1][7]);check(!$GLOBALS['calls'],'delete waits until deletion finishes');fire('shutdown');check(in_array(home_url('/old/'),files()),'deleted public URL retained');
reset_state();fire('future_to_publish',get_post(7));fire('save_post',7,get_post(7),true);fire('shutdown');check(count($GLOBALS['calls'])===1,'scheduled publish deduplicated');
reset_state();$GLOBALS['responses']=[['code'=>200,'body'=>'{"success":true}'],['code'=>503,'body'=>'{"success":false,"errors":[{"code":1000,"message":"secret-test-token"}]}']];$urls=array_map(fn($i)=>home_url('/p'.$i),range(1,31));$r=P::purge_urls_for_current_site($urls);check($r[0]['success']&&!$r[1]['success']&&!empty($r[1]['queued']),'partial failure remains pending');check(count(jobs())===1,'only failed batch retained');P::log_site_purge('test','zone-1',$urls,$r);check(strpos(json_encode(get_site_option('acfcm_purge_log')),'secret-test-token')===false,'log excludes API text and token');retry_now();check(count($GLOBALS['calls'])===3&&count($GLOBALS['calls'][2][2]['files'])===1&&!jobs(),'retry sends failed batch only');
reset_state();$GLOBALS['responses']=[['code'=>503,'body'=>'{}']];P::purge_urls_for_current_site([home_url('/a')]);P::purge_urls_for_current_site([home_url('/a')]);check(count(jobs())===1&&count($GLOBALS['calls'])===1,'pending payload deduplicated');$j=array_values(jobs())[0];check($j['due']>=time()+59,'exponential backoff starts at 60 seconds');
reset_state();$GLOBALS['responses']=[['code'=>429,'body'=>'{}','retry-after'=>'900']];P::purge_urls_for_current_site([home_url('/a')]);P::purge_urls_for_current_site([home_url('/b')]);check(count($GLOBALS['calls'])===1,'429 shared-token cooldown stops new requests');check(array_values(jobs())[0]['due']>=time()+899,'Retry-After honored');
reset_state();$GLOBALS['responses']=array_fill(0,6,['code'=>503,'body'=>'{}']);P::purge_urls_for_current_site([home_url('/a')]);for($i=0;$i<5;$i++)retry_now();check(count($GLOBALS['calls'])===5&&!jobs(),'retries stop after five attempts');
reset_state();$GLOBALS['responses']=[['code'=>403,'body'=>'{}']];P::purge_urls_for_current_site([home_url('/a')]);check(!jobs(),'permission failure is terminal');
reset_state();$GLOBALS['during_http']=function(){P::purge_urls_for_current_site([home_url('/a')]);};P::purge_urls_for_current_site([home_url('/a')]);check(count(jobs())===1,'edit during in-flight purge survives completion');retry_now();check(count($GLOBALS['calls'])===2&&!jobs(),'newer edit receives trailing purge');
reset_state();$GLOBALS['multi']=true;fire('pre_post_update',7);get_post(7)->post_name='one';switch_to_blog(2);update_option('cloudflare_zone_id','zone-2');update_option('cloudflare_api_token','second-secret');$GLOBALS['posts'][2][7]=(object)['ID'=>7,'post_status'=>'publish','post_type'=>'post','post_name'=>'two','post_author'=>2];fire('save_post',7,get_post(7),true);restore_current_blog();fire('shutdown');check(count($GLOBALS['calls'])===2&&$GLOBALS['calls'][0][0]===1&&$GLOBALS['calls'][1][0]===2,'multisite same post ID isolated');check(strpos($GLOBALS['calls'][1][1],'/zone-2/')!==false&&get_current_blog_id()===1,'multisite zone and context restored');
reset_state();$GLOBALS['schedule_fail']=true;$r=P::purge_urls_for_current_site([home_url('/a')]);unset($GLOBALS['schedule_fail']);check(!$GLOBALS['calls']&&!$r[0]['success'],'scheduler failure cannot report success');
reset_state();check(P::log_url('https://user:password@example.test/path?token=secret#private')==='https://example.test/path','log URLs omit query, fragment and credentials');
reset_state();$GLOBALS['responses']=[new WP_Error()];$r=P::purge_urls_for_current_site([home_url('/a')]);check(!$r[0]['success']&&!empty($r[0]['queued']),'transport error retries');
reset_state();$GLOBALS['responses']=[['code'=>200,'body'=>'invalid JSON']];$r=P::purge_urls_for_current_site([home_url('/a')]);check(!$r[0]['success']&&!empty($r[0]['queued']),'malformed success response retries');
reset_state();$GLOBALS['responses']=[['code'=>503,'body'=>'{}']];P::purge_urls_for_current_site([home_url('/a')]);update_option('cloudflare_zone_id','changed');retry_now();check(count($GLOBALS['calls'])===1&&!jobs(),'changed zone cancels pending purge');
reset_state();$GLOBALS['responses']=[['code'=>503,'body'=>'{}']];P::purge_urls_for_current_site([home_url('/a')]);foreach(jobs() as $k=>$j){$j['created']=time()-DAY_IN_SECONDS;update_option($k,$j);}retry_now();check(count($GLOBALS['calls'])===1&&!jobs(),'24-hour expiry sends no request');
reset_state();$GLOBALS['responses']=array_fill(0,101,['code'=>503,'body'=>'{}']);for($i=0;$i<101;$i++)$r=P::purge_urls_for_current_site([home_url('/'.$i)]);check(count(jobs())===100&&count($GLOBALS['calls'])===100&&!$r[0]['success']&&empty($r[0]['queued']),'queue capacity fails visibly without extra HTTP');
reset_state();$GLOBALS['responses']=array_fill(0,2,['code'=>503,'body'=>'{}']);P::purge_urls_for_current_site([home_url('/a')]);P::purge_urls_for_current_site([home_url('/b')]);$j=get_option('acfcm_purge_job_0');$j['due']=time()-1;update_option('acfcm_purge_job_0',$j);P::retry_purge('acfcm_purge_job_0',$j['id']);P::purge_urls_for_current_site([home_url('/b')]);check(count(jobs())===1&&count($GLOBALS['calls'])===3,'dedup survives a freed earlier queue slot');
function wp_list_pluck($items,$field){return array_column($items,$field);}
function get_sites($args){return [1,2];} function get_bloginfo($v){return 'Test site';} function get_home_url($id,$p){return 'https://site'.$id.'.test'.$p;}
check(P::retry_after_seconds(gmdate('D, d M Y H:i:s',time()+600).' GMT')>=599,'HTTP-date Retry-After parsed');
$source=file_get_contents(dirname(__DIR__).'/acquire-cloudflare-cache-manager.php');preg_match('/Version:\s+(\S+)/',$source,$m);check($m[1]===P::VERSION&&'v'.P::VERSION==='v3.7.4','header constant and future release tag aligned');
echo "All purge regression tests passed.\n";
